import { authorCuratedProblem } from "../curated-authoring.js";
import { makeEulerCandidateSpec } from "./oxford-euler-authoring.js";

export const oxfordEulerKioskGridModelSpec = makeEulerCandidateSpec({
  "id":"oxford-euler-kiosk-grid-model","title":"How Dense Should a Kiosk Grid Be?","category":"modelling","topics":["mathematical modelling","2D spacing","optimization","assumption checking"],
  "prompt":"A square exhibition hall has side length L. You are considering an m by m grid of information kiosks, one at the center of each equal square cell. Visitors are spread uniformly and walk along north-south/east-west aisles at speed v to the kiosk in their cell. Staffing each kiosk has a resource penalty tau measured in the same weighted objective as one unit of visitor time. Build and analyze a model for choosing m. Then explain which conclusions are robust if visitors instead walk straight-line paths or are not uniformly distributed.",
  "givenInformation":["Treat m as a positive integer in the actual decision, but a continuous relaxation is allowed as an intermediate model.","The weighting that converts staffing resources into the same objective units as visitor time is a modelling choice, not a physical law."],
  "domains":["algebra","functions","calculus"],"contentConcepts":["parameter-dependent-algebra","optimization-extrema","rate-change"],"prerequisiteConcepts":["arithmetic","algebraic-manipulation","differentiation"],
  "skills":["modelling","representation-switching","strategic-simplification","proof-construction","precision-checking","case-analysis","generalization","transfer"],"difficulty":{"entry":"introductory","core":"standard","ceiling":"strong"},"novelty":"high","abstraction":"moderate","introducesNewDefinition":false,
  "stages":[
    {"id":"quantities","description":"Choose m as the decision variable and separate access cost from staffing cost, discarding irrelevant absolute hall position.","contentConcepts":["parameter-dependent-algebra"],"skills":["modelling","strategic-simplification"],"difficulty":"introductory","novelty":"moderate","abstraction":"moderate"},
    {"id":"walking","description":"For one cell of side d=L/m, derive mean Manhattan distance d/2 to its center and hence mean walking time L/(2vm).","contentConcepts":["parameter-dependent-algebra"],"skills":["representation-switching","proof-construction"],"difficulty":"standard","novelty":"moderate","abstraction":"moderate"},
    {"id":"objective","description":"Combine walking and staffing into J(m)=L/(2vm)+tau m^2 and interpret every term and unit.","contentConcepts":["parameter-dependent-algebra"],"skills":["modelling","precision-checking"],"difficulty":"standard","novelty":"high","abstraction":"moderate"},
    {"id":"optimize","description":"Use the continuous relaxation to locate m^3=L/(4v tau), then return to nearby positive integers.","contentConcepts":["optimization-extrema","rate-change"],"skills":["proof-construction","precision-checking","case-analysis"],"difficulty":"standard","novelty":"high","abstraction":"moderate"},
    {"id":"transfer","description":"Change walking geometry or demand density and identify which derivation step, rather than merely which constant, must change.","contentConcepts":["parameter-dependent-algebra","optimization-extrema"],"skills":["generalization","transfer","modelling"],"difficulty":"strong","novelty":"high","abstraction":"high"}
  ],
  "commonErrors":[{"id":"one-dimensional-spacing","description":"Uses a one-dimensional nearest-stop distance and misses that kiosk count grows like m^2."},{"id":"continuous-is-integer","description":"Reports the real cube-root optimizer as an implementable kiosk count without comparing nearby integers."}],
  "followUps":["How should the answer scale if the hall side doubles while v and tau stay fixed?","What evidence would you want before trusting the uniform-demand assumption?"],
  "extensions":[{"id":"euclidean-walking","prompt":"Replace Manhattan walking by straight-line walking inside each square cell. Which scaling law for optimal m survives even if the exact mean distance constant is not computed?"},{"id":"hotspot-demand","prompt":"Suppose half the visitors are concentrated in one quarter of the hall. Propose a nonuniform placement model and explain what the equal-grid model misses."}],
  "hints":[
    {"text":"If the cells have side d=L/m, analyze one representative cell rather than the whole hall.","formulations":["use symmetry to reduce to one square cell","cell side length is L divided by m"]},
    {"text":"For X uniform on [-d/2,d/2], E|X|=d/4; Manhattan distance adds the two coordinate contributions.","formulations":["average horizontal and vertical displacement separately","mean Manhattan distance to the cell center is d/2"]},
    {"text":"The two model terms scale like 1/m and m^2.","formulations":["access improves inversely with grid resolution","staffing grows with the number of kiosks"]},
    {"text":"For the continuous relaxation J(m)=A/m+tau m^2, set J prime to zero.","formulations":["differentiate before rounding","the balance occurs when A/m^2 equals 2 tau m"]},
    {"text":"The stationary equation gives m^3=L/(4v tau); compare neighboring integers and then audit assumptions.","formulations":["the optimizer has a cube-root scaling","return from the relaxation to the discrete decision"]}
  ],
  "canonicalSolution":"With m cells along each side, a cell has side d=L/m. Center coordinates relative to one cell are uniform on [-d/2,d/2]^2. Under axis-aligned walking, E|X|=d/4 and E|Y|=d/4, so mean distance is d/2 and mean walk time is L/(2vm). There are m^2 kiosks, so the stated time-equivalent staffing penalty contributes tau m^2. Thus J(m)=L/(2vm)+tau m^2. For m>0 treated continuously, J prime(m)=-L/(2v m^2)+2 tau m, giving m^3=L/(4v tau). The actual choice compares the positive integers around this value. Larger halls favor denser grids, faster walking favors fewer kiosks, and larger staffing penalty favors fewer kiosks with cube-root sensitivity. Straight-line walking changes the constant in the 1/m access term but not the 1/m scaling, so the cube-root scaling survives. Nonuniform demand can invalidate equal cells and requires spatial weighting or nonuniform placement.",
  "verificationNotes":"The mean Manhattan distance d/2 follows from two independent coordinate expectations but independence is not actually required for linearity of expectation. Staffing penalty tau is explicitly a weighted objective coefficient. The continuous stationary point is the unique global minimum because J decreases then increases for positive m; integer rounding must be checked."
} as const);

export const oxfordEulerKioskGridModelEntry = authorCuratedProblem(oxfordEulerKioskGridModelSpec);
