import { authorCuratedProblem, type CuratedProblemSpec } from "../../curated-authoring.js";
import { DIRICHLET_CANDIDATE_REVIEW_NOTES, evidence, makeDirichletAdaptive } from "./support.js";

export const oxfordDThreeReversalPermutationsSpec: CuratedProblemSpec = {
  id: "oxford-d-three-reversal-permutations",
  title: "Permutations Generated by Reversing Three Consecutive Cards",
  mode: "OXFORD_MATHEMATICS",
  category: "combinatorics",
  topics: ["permutations", "invariants", "constructive reachability"],
  difficulty: "uncalibrated-oxford-candidate",
  prompt: "Cards 1,2,...,n begin in that order in a row. A move reverses any three consecutive positions. Characterize exactly which final orders are reachable, count them, and determine the minimum number of moves needed for a reachable target in terms of a natural statistic.",
  givenInformation: ["Reversing positions i,i+1,i+2 swaps the cards in positions i and i+2 and leaves the middle card in place.", "Assume n>=3."],
  approaches: [{ id: "parity-subsequences", label: "Separate odd and even positions, then recognize moves as adjacent swaps inside those two subsequences" }],
  milestones: [
    { id: "inspect-single-reversal", description: "Notice that each move swaps two positions of the same parity and leaves every card on the same position parity it started on.", approachIds: ["parity-subsequences"], hintLevels: [1] },
    { id: "state-parity-obstruction", description: "Prove position parity of each individual card is an invariant, giving a necessary reachability condition.", approachIds: ["parity-subsequences"], prerequisiteIds: ["inspect-single-reversal"], hintLevels: [2] },
    { id: "reinterpret-as-adjacent-swaps", description: "Read the odd positions as one subsequence and even positions as another; show a legal reversal is exactly an adjacent swap in one of these subsequences.", approachIds: ["parity-subsequences"], prerequisiteIds: ["state-parity-obstruction"], hintLevels: [3] },
    { id: "construct-all-parity-preserving-targets", description: "Use adjacent swaps to realize any independent permutation of the odd-position cards and of the even-position cards.", approachIds: ["parity-subsequences"], prerequisiteIds: ["reinterpret-as-adjacent-swaps"], hintLevels: [4] },
    { id: "count-and-minimize-moves", description: "Count reachable orders and show the minimum move count is the sum of inversion counts in the induced odd and even subsequence permutations.", approachIds: ["parity-subsequences"], prerequisiteIds: ["construct-all-parity-preserving-targets"], hintLevels: [5] }
  ],
  edges: [
    { from: "inspect-single-reversal", to: "state-parity-obstruction" },
    { from: "state-parity-obstruction", to: "reinterpret-as-adjacent-swaps" },
    { from: "reinterpret-as-adjacent-swaps", to: "construct-all-parity-preserving-targets" },
    { from: "construct-all-parity-preserving-targets", to: "count-and-minimize-moves" }
  ],
  commonErrors: [
    { id: "global-permutation-parity", description: "Tracks only whether the whole card permutation is even or odd; each move is a transposition, so global sign changes and is not invariant." },
    { id: "position-not-card-parity", description: "Says the set of odd positions stays fixed, which is tautological; the real invariant is which cards occupy odd versus even positions." },
    { id: "sufficiency-without-generation", description: "States that preserving card-position parity is sufficient without proving the length-three reversals generate arbitrary permutations inside each parity subsequence." }
  ],
  followUps: ["How many reachable orders are there when n is odd versus even?", "What is the farthest reachable target in minimum-move distance?"],
  extensions: [
    { id: "maximum-minimum-moves", prompt: "Use inversion counts to determine the largest possible minimum number of moves among reachable targets." },
    { id: "add-length-two-swap", prompt: "If ordinary reversal of two consecutive cards is also allowed, explain why every permutation becomes reachable." }
  ],
  hints: [
    { level: 1, text: "A reversal of three positions does not really reverse three independent places: it simply swaps the first and third positions.", formulations: ["the middle card stays put", "the move is a distance-two swap"] },
    { level: 2, text: "Positions i and i+2 have the same parity. Therefore every card always remains in a position with the same parity as its starting position.", formulations: ["card-position parity is invariant", "odd-start cards remain in odd slots"] },
    { level: 3, text: "Compress the odd positions into one list and the even positions into another. A move starting at an odd index swaps adjacent entries of the odd list; a move starting at an even index does the same for the even list.", formulations: ["two independent adjacent-swap systems", "reindex by parity"] },
    { level: 4, text: "Adjacent swaps generate every permutation of a list, so the parity condition is also sufficient.", formulations: ["bubble-sort each parity subsequence", "construct any allowed target"] },
    { level: 5, text: "Each move changes the inversion count of exactly one parity subsequence by one. Bubble sort attains the target in exactly the total number of those inversions.", formulations: ["minimum moves equals two inversion counts added", "use adjacent-swap distance"] }
  ],
  canonicalSolution: "Reversing positions i,i+1,i+2 swaps the cards in positions i and i+2 and fixes the middle position. Since i and i+2 have the same parity, each card remains forever in positions of the same parity as its initial position. Thus a necessary condition is that cards originally in odd positions occupy the odd positions in the target, and similarly for even positions. Now compress the odd positions 1,3,5,... into one list and the even positions 2,4,6,... into a second list. A move beginning at an odd index swaps two adjacent entries in the odd-position list; a move beginning at an even index swaps two adjacent entries in the even-position list. Hence arbitrary adjacent swaps are available independently in both lists, so every parity-preserving target is reachable. There are ceil(n/2)! choices for the odd-position order and floor(n/2)! for the even-position order. For a fixed reachable target, let I_odd and I_even be the inversion counts of the target permutations in the two compressed lists. Every legal move is one adjacent transposition in exactly one list, so it changes the corresponding inversion count by exactly 1 and at least I_odd+I_even moves are needed. Bubble sorting the two lists separately achieves the target in exactly that many moves. Thus the minimum is I_odd+I_even.",
  verificationNotes: "For n=3, the reachable orders are exactly the two orders obtained by optionally swapping cards 1 and 3, matching 2!*1!=2. Global permutation sign is not invariant because each move is one transposition. The minimum-move statement uses the standard adjacent-swap inversion metric separately on the two parity subsequences.",
  reviewStatus: "expert-review",
  reviewNotes: DIRICHLET_CANDIDATE_REVIEW_NOTES,
  oxfordAdaptive: makeDirichletAdaptive({
    familyId: "oxford-d-three-reversal-permutations",
    domains: ["combinatorics"],
    contentConcepts: ["parity", "counting-structure"],
    prerequisiteConcepts: ["counting-principles", "arithmetic"],
    skillEvidence: [evidence("small-case-exploration", "supporting"), evidence("invariants", "primary"), evidence("representation-switching", "primary"), evidence("proof-construction", "primary"), evidence("technique", "supporting"), evidence("precision-checking", "supporting")],
    difficulty: { entry: "introductory", core: "standard", ceiling: "strong" },
    novelty: "high",
    abstraction: "low",
    introducesNewDefinition: false,
    provenance: { originType: "classic-problem", sourceCategory: "classic-mathematics" },
    stages: [
      { id: "three-reversal-opening", role: "warm-up", prerequisiteStageIds: [], domains: ["combinatorics"], contentConcepts: ["parity"], skillEvidence: [evidence("small-case-exploration", "primary"), evidence("invariants", "supporting")], milestones: [{ milestoneId: "inspect-single-reversal", skillEvidence: [evidence("small-case-exploration", "primary")], contentConcepts: ["parity"] }], extensionIds: [], difficulty: "introductory" },
      { id: "three-reversal-core", role: "core", prerequisiteStageIds: ["three-reversal-opening"], domains: ["combinatorics"], contentConcepts: ["parity", "counting-structure"], skillEvidence: [evidence("invariants", "primary"), evidence("representation-switching", "primary"), evidence("proof-construction", "primary")], milestones: [
        { milestoneId: "state-parity-obstruction", skillEvidence: [evidence("invariants", "primary")], contentConcepts: ["parity"] },
        { milestoneId: "reinterpret-as-adjacent-swaps", skillEvidence: [evidence("representation-switching", "primary")], contentConcepts: ["parity"] },
        { milestoneId: "construct-all-parity-preserving-targets", skillEvidence: [evidence("proof-construction", "primary")], contentConcepts: ["counting-structure"] }
      ], extensionIds: [], difficulty: "standard" },
      { id: "three-reversal-transfer", role: "transfer", prerequisiteStageIds: ["three-reversal-core"], domains: ["combinatorics"], contentConcepts: ["parity", "counting-structure"], skillEvidence: [evidence("technique", "primary"), evidence("precision-checking", "supporting")], milestones: [{ milestoneId: "count-and-minimize-moves", skillEvidence: [evidence("technique", "primary"), evidence("precision-checking", "supporting")], contentConcepts: ["counting-structure"] }], extensionIds: ["maximum-minimum-moves", "add-length-two-swap"], difficulty: "strong"
      }
    ]
  })
};
export const oxfordDThreeReversalPermutationsEntry = authorCuratedProblem(oxfordDThreeReversalPermutationsSpec);

export const oxfordDDivisorStepGeometrySpec: CuratedProblemSpec = {
  id: "oxford-d-divisor-step-geometry",
  title: "Geometry of the Divisor-Step Graph",
  mode: "OXFORD_MATHEMATICS",
  category: "number theory",
  topics: ["prime factorization", "graph distance", "counting paths"],
  difficulty: "uncalibrated-oxford-candidate",
  prompt: "Fix a positive integer N. Make a graph whose vertices are the positive divisors of N, joining two divisors when the larger divided by the smaller is a prime. Using the prime factorization of N, determine the distance between any two vertices, count the shortest paths between them, and find the graph diameter.",
  givenInformation: ["You may use unique prime factorization.", "Graph distance means the minimum number of edges in a path."],
  approaches: [{ id: "exponent-lattice", label: "Represent each divisor by its vector of prime exponents" }],
  milestones: [
    { id: "draw-small-divisor-graphs", description: "Draw the graph for N=12 or N=18 and notice a rectangular exponent-grid structure.", approachIds: ["exponent-lattice"], hintLevels: [1] },
    { id: "encode-exponent-vectors", description: "Write N=prod p_i^{a_i} and each divisor d as an exponent vector (b_i) with 0<=b_i<=a_i.", approachIds: ["exponent-lattice"], prerequisiteIds: ["draw-small-divisor-graphs"], hintLevels: [2] },
    { id: "identify-edge-coordinate-change", description: "Show adjacent divisors differ by exactly 1 in one exponent coordinate and agree in all others.", approachIds: ["exponent-lattice"], prerequisiteIds: ["encode-exponent-vectors"], hintLevels: [3] },
    { id: "derive-distance-and-path-count", description: "Prove distance is sum_i |b_i-c_i| and count shortest paths by ordering the required coordinate changes.", approachIds: ["exponent-lattice"], prerequisiteIds: ["identify-edge-coordinate-change"], hintLevels: [4] },
    { id: "find-diameter-and-bipartition", description: "Maximize the distance to get sum_i a_i and show parity of the total exponent sum gives a natural bipartition.", approachIds: ["exponent-lattice"], prerequisiteIds: ["derive-distance-and-path-count"], hintLevels: [5] }
  ],
  edges: [
    { from: "draw-small-divisor-graphs", to: "encode-exponent-vectors" },
    { from: "encode-exponent-vectors", to: "identify-edge-coordinate-change" },
    { from: "identify-edge-coordinate-change", to: "derive-distance-and-path-count" },
    { from: "derive-distance-and-path-count", to: "find-diameter-and-bipartition" }
  ],
  commonErrors: [
    { id: "prime-quotient-any-direction", description: "Forgets adjacency requires one divisor to divide the other with prime quotient; exponent vectors make the direction-free edge condition precise." },
    { id: "euclidean-distance", description: "Uses Euclidean distance between exponent vectors; each edge changes one coordinate by one, so the graph metric is the L1 distance." },
    { id: "path-count-forgets-repetitions", description: "Counts all L! orders of coordinate changes without dividing by factorials for repeated moves in the same coordinate." }
  ],
  followUps: ["How many vertices does the graph have?", "When is the divisor-step graph a tree?"],
  extensions: [
    { id: "vertex-count", prompt: "Recover the usual divisor-count formula prod_i(a_i+1) from the exponent-grid representation." },
    { id: "tree-classification", prompt: "Classify N for which the divisor-step graph is a tree." }
  ],
  hints: [
    { level: 1, text: "The divisors of N differ only in their prime exponents. Try placing a divisor at the coordinate vector of those exponents.", formulations: ["turn divisors into lattice points", "use prime-exponent coordinates"] },
    { level: 2, text: "If N=prod p_i^{a_i}, a divisor is exactly a vector (b_i) with 0<=b_i<=a_i.", formulations: ["bounded exponent vectors", "divisor set is a box of lattice points"] },
    { level: 3, text: "Multiplying or dividing by one prime changes exactly one coordinate by 1.", formulations: ["edges are unit coordinate steps", "the graph is a Cartesian grid"] },
    { level: 4, text: "To go from b to c, each coordinate i must change |b_i-c_i| times. Any shortest path is just an ordering of these required moves.", formulations: ["distance is an L1 sum", "count shortest paths with a multinomial coefficient"] },
    { level: 5, text: "The largest possible coordinate difference is a_i in coordinate i, attained between 1 and N. Every edge changes the parity of the sum of exponents.", formulations: ["diameter is the total prime-exponent count", "Omega parity bipartitions the graph"] }
  ],
  canonicalSolution: "Write N=prod_{i=1}^r p_i^{a_i}. Each divisor d corresponds uniquely to an exponent vector b=(b_1,...,b_r) with 0<=b_i<=a_i. Two divisors are adjacent exactly when one exponent vector is obtained from the other by adding or subtracting 1 in exactly one coordinate. Therefore any path from b to c must change coordinate i at least |b_i-c_i| times, so its length is at least L=sum_i|b_i-c_i|. Changing each coordinate monotonically toward its target realizes a path of exactly L steps, so the distance is L. Let delta_i=|b_i-c_i|. A shortest path consists of L moves, with delta_i indistinguishable moves in coordinate i, so the number is L!/(prod_i delta_i!). The distance is maximized by taking opposite corners of the exponent box, for example 1=(0,...,0) and N=(a_1,...,a_r), giving diameter sum_i a_i. Finally every edge changes the parity of sum_i b_i, so the graph is bipartite according to whether the total prime-exponent count Omega(d) is even or odd. The graph is a tree exactly when at most one exponent a_i is nonzero; with two positive coordinates the exponent box contains a 4-cycle.",
  verificationNotes: "The path-count formula treats moves in the same coordinate as indistinguishable and is valid because a shortest path never moves away from the target in any coordinate. The diameter is Omega(N)=sum a_i. For N=1 the graph has one vertex and diameter 0; the tree extension should either include this trivial case or state N>1.",
  reviewStatus: "expert-review",
  reviewNotes: DIRICHLET_CANDIDATE_REVIEW_NOTES,
  oxfordAdaptive: makeDirichletAdaptive({
    familyId: "oxford-d-divisor-step-geometry",
    domains: ["number-theory", "graph-theory", "combinatorics"],
    contentConcepts: ["prime-structure", "divisibility", "paths-cycles-connectivity", "counting-structure"],
    prerequisiteConcepts: ["prime-factorization", "divisibility", "graph-basics", "counting-principles"],
    skillEvidence: [evidence("visualization", "supporting"), evidence("representation-switching", "primary"), evidence("proof-construction", "primary"), evidence("technique", "supporting"), evidence("generalization", "supporting"), evidence("small-case-exploration", "supporting"), evidence("precision-checking", "supporting")],
    difficulty: { entry: "introductory", core: "standard", ceiling: "strong" },
    novelty: "high",
    abstraction: "moderate",
    introducesNewDefinition: true,
    provenance: { originType: "classic-problem", sourceCategory: "classic-mathematics" },
    stages: [
      { id: "divisor-geometry-opening", role: "warm-up", prerequisiteStageIds: [], domains: ["number-theory", "graph-theory", "combinatorics"], contentConcepts: ["prime-structure", "divisibility", "paths-cycles-connectivity"], skillEvidence: [evidence("visualization", "primary"), evidence("small-case-exploration", "supporting")], milestones: [{ milestoneId: "draw-small-divisor-graphs", skillEvidence: [evidence("visualization", "primary"), evidence("small-case-exploration", "supporting")], contentConcepts: ["divisibility", "paths-cycles-connectivity"] }], extensionIds: [], difficulty: "introductory", introducesNewDefinition: true },
      { id: "divisor-geometry-core", role: "core", prerequisiteStageIds: ["divisor-geometry-opening"], domains: ["number-theory", "graph-theory", "combinatorics"], contentConcepts: ["prime-structure", "divisibility", "paths-cycles-connectivity", "counting-structure"], skillEvidence: [evidence("representation-switching", "primary"), evidence("proof-construction", "primary"), evidence("technique", "supporting")], milestones: [
        { milestoneId: "encode-exponent-vectors", skillEvidence: [evidence("representation-switching", "primary")], contentConcepts: ["prime-structure", "divisibility"] },
        { milestoneId: "identify-edge-coordinate-change", skillEvidence: [evidence("proof-construction", "supporting")], contentConcepts: ["paths-cycles-connectivity"] },
        { milestoneId: "derive-distance-and-path-count", skillEvidence: [evidence("proof-construction", "primary"), evidence("technique", "supporting")], contentConcepts: ["counting-structure", "paths-cycles-connectivity"] }
      ], extensionIds: [], difficulty: "standard" },
      { id: "divisor-geometry-transfer", role: "transfer", prerequisiteStageIds: ["divisor-geometry-core"], domains: ["number-theory", "graph-theory", "combinatorics"], contentConcepts: ["prime-structure", "divisibility", "paths-cycles-connectivity", "counting-structure"], skillEvidence: [evidence("generalization", "primary"), evidence("precision-checking", "supporting")], milestones: [{ milestoneId: "find-diameter-and-bipartition", skillEvidence: [evidence("generalization", "primary"), evidence("precision-checking", "supporting")], contentConcepts: ["paths-cycles-connectivity", "prime-structure"] }], extensionIds: ["vertex-count", "tree-classification"], difficulty: "strong"
      }
    ]
  })
};
export const oxfordDDivisorStepGeometryEntry = authorCuratedProblem(oxfordDDivisorStepGeometrySpec);

export const oxfordDTripleFlipCircleSpec: CuratedProblemSpec = {
  id: "oxford-d-triple-flip-circle",
  title: "Three-Consecutive Lamp Flips on a Circle",
  mode: "OXFORD_MATHEMATICS",
  category: "combinatorics",
  topics: ["parity", "cyclic processes", "reachability"],
  difficulty: "uncalibrated-oxford-candidate",
  prompt: "There are n>=3 lamps in a circle, initially all off. A move chooses three consecutive lamps and flips all three. Characterize exactly which on/off configurations are reachable. Your answer should split according to whether 3 divides n, and should also determine how many different subsets of moves produce a reachable target.",
  givenInformation: ["Flipping the same lamp twice cancels, so only the parity of how many times each move is used matters.", "There are n possible moves, one starting at each lamp."],
  approaches: [{ id: "move-parity-recurrence", label: "Encode move choices modulo 2, analyze the homogeneous period-three recurrence, then match it with a visible invariant" }],
  milestones: [
    { id: "explore-small-circles", description: "Check n=3,4,5,6 and notice a sharp change when n is divisible by 3.", approachIds: ["move-parity-recurrence"], hintLevels: [1] },
    { id: "encode-move-equations", description: "Let y_i record whether move i is used and derive x_i=y_i+y_{i-1}+y_{i-2} mod 2 for the final lamp states.", approachIds: ["move-parity-recurrence"], prerequisiteIds: ["explore-small-circles"], hintLevels: [2] },
    { id: "analyze-zero-effect-moves", description: "For x=0 derive y_i=y_{i-1}+y_{i-2}, show every solution has period 3, and count the zero-effect move sets according to n mod 3.", approachIds: ["move-parity-recurrence"], prerequisiteIds: ["encode-move-equations"], hintLevels: [3] },
    { id: "classify-reachability", description: "If 3 does not divide n, use injective counting to reach every configuration; if 3 divides n, identify the three residue-class lamp parities that must agree.", approachIds: ["move-parity-recurrence"], prerequisiteIds: ["analyze-zero-effect-moves"], hintLevels: [4] },
    { id: "prove-sufficiency-by-counting", description: "When 3 divides n, count both the reachable image and the configurations satisfying equal residue-class parities to prove the invariant is complete, and count move-set multiplicity.", approachIds: ["move-parity-recurrence"], prerequisiteIds: ["classify-reachability"], hintLevels: [5] }
  ],
  edges: [
    { from: "explore-small-circles", to: "encode-move-equations" },
    { from: "encode-move-equations", to: "analyze-zero-effect-moves" },
    { from: "analyze-zero-effect-moves", to: "classify-reachability" },
    { from: "classify-reachability", to: "prove-sufficiency-by-counting" }
  ],
  commonErrors: [
    { id: "counts-move-sequences-not-subsets", description: "Treats order or repeated use of moves as distinct even though only move parity affects the final configuration." },
    { id: "period-three-without-cycle-closure", description: "Finds the period-three recurrence for zero-effect choices but forgets to impose consistency after wrapping around n positions." },
    { id: "invariant-only", description: "When 3 divides n, proves equal residue-class parities are necessary but not sufficient; the image-size count supplies completeness." }
  ],
  followUps: ["Why are there exactly four zero-effect move subsets when 3 divides n?", "What changes if a move flips two consecutive lamps instead?"],
  extensions: [
    { id: "two-lamp-transfer", prompt: "If a move flips two consecutive lamps on the circle, prove the reachable configurations are exactly those with an even total number of on lamps." },
    { id: "move-multiplicity", prompt: "Show every reachable target has exactly one realizing move subset when 3 does not divide n and exactly four when 3 divides n." }
  ],
  hints: [
    { level: 1, text: "Ignore move order and record only whether each of the n possible triple-flips is used an odd or even number of times.", formulations: ["work modulo two on move choices", "one bit per move"] },
    { level: 2, text: "Lamp i is flipped by exactly the moves starting at i,i-1,i-2, so x_i=y_i+y_{i-1}+y_{i-2} modulo 2.", formulations: ["write the local move equation", "each lamp sees three neighboring move bits"] },
    { level: 3, text: "A move subset with no net effect satisfies y_i=y_{i-1}+y_{i-2}. Over bits, starting values a,b generate the repeating pattern a,b,a+b,a,b,a+b,... .", formulations: ["the homogeneous recurrence has period three", "zero-effect patterns repeat every three positions"] },
    { level: 4, text: "If 3 does not divide n, cyclic closure forces a=b=0, so different move subsets give different outcomes. If 3 divides n, each move flips one lamp in each index class modulo 3, so the three class parities always remain equal.", formulations: ["injectivity off multiples of three", "three class parities give the obstruction"] },
    { level: 5, text: "For 3|n there are four zero-effect move subsets, so there are 2^{n-2} reachable outcomes. Equal parity in the three residue classes imposes exactly two independent parity constraints, leaving exactly 2^{n-2} configurations.", formulations: ["matching counts proves sufficiency", "kernel size four gives image size two to the n minus two"] }
  ],
  canonicalSolution: "Let y_i in {0,1} indicate whether the move starting at lamp i is used an odd number of times, and let x_i be the final state of lamp i. Indices are cyclic. Lamp i is affected by moves i,i-1,i-2, so x_i=y_i+y_{i-1}+y_{i-2} mod 2. First study move subsets with zero net effect. Then y_i=y_{i-1}+y_{i-2}. Starting from y_1=a,y_2=b, the recurrence gives a,b,a+b,a,b,a+b,..., a period-three pattern. If 3 does not divide n, cyclic consistency forces a=b=0, so the only zero-effect move subset is the empty one. Therefore the map from the 2^n move subsets to the 2^n lamp configurations is injective and hence bijective: every configuration is reachable, uniquely. Now suppose 3 divides n. Every choice of a,b gives a cyclic period-three zero-effect pattern, so there are exactly four zero-effect move subsets. Hence the number of reachable outcomes is 2^n/4=2^{n-2}, and every reachable target has exactly four realizing move subsets. Also partition the lamps by their indices modulo 3. Every triple-consecutive move flips exactly one lamp in each class, so the three class parities always toggle together; starting from all zero, every reachable target has the three class parities equal. These equalities impose two independent parity constraints, so exactly 2^{n-2} configurations satisfy them. Since the reachable set is contained in this set and has the same size, the condition is sufficient. Thus: if 3 does not divide n, every configuration is reachable uniquely; if 3 divides n, exactly the configurations with equal on-parity in the three mod-3 position classes are reachable, each in four move subsets.",
  verificationNotes: "For n=3 the condition gives only 000 and 111, and the four move subsets collapse to the same two outcomes with multiplicity four, as expected because all three moves flip the same three lamps. For 3∤n the homogeneous period-three pattern is incompatible with cyclic length n unless a=b=0. The counting proof treats move subsets modulo repeated use/order, exactly as stated in the prompt.",
  reviewStatus: "expert-review",
  reviewNotes: DIRICHLET_CANDIDATE_REVIEW_NOTES,
  oxfordAdaptive: makeDirichletAdaptive({
    familyId: "oxford-d-triple-flip-circle",
    domains: ["combinatorics", "number-theory", "sequences-recurrences"],
    contentConcepts: ["parity", "modular-reasoning", "counting-structure", "recurrence-structure"],
    prerequisiteConcepts: ["modular-arithmetic", "counting-principles"],
    skillEvidence: [evidence("small-case-exploration", "primary"), evidence("representation-switching", "primary"), evidence("invariants", "primary"), evidence("proof-construction", "primary"), evidence("precision-checking", "supporting"), evidence("generalization", "supporting")],
    difficulty: { entry: "introductory", core: "strong", ceiling: "strong" },
    novelty: "high",
    abstraction: "moderate",
    introducesNewDefinition: false,
    provenance: { originType: "classic-problem", sourceCategory: "classic-mathematics" },
    stages: [
      { id: "triple-flip-opening", role: "warm-up", prerequisiteStageIds: [], domains: ["combinatorics", "number-theory"], contentConcepts: ["parity", "modular-reasoning"], skillEvidence: [evidence("small-case-exploration", "primary")], milestones: [{ milestoneId: "explore-small-circles", skillEvidence: [evidence("small-case-exploration", "primary")], contentConcepts: ["parity"] }], extensionIds: [], difficulty: "introductory" },
      { id: "triple-flip-core", role: "core", prerequisiteStageIds: ["triple-flip-opening"], domains: ["combinatorics", "number-theory", "sequences-recurrences"], contentConcepts: ["parity", "modular-reasoning", "counting-structure", "recurrence-structure"], skillEvidence: [evidence("representation-switching", "primary"), evidence("invariants", "primary"), evidence("proof-construction", "primary")], milestones: [
        { milestoneId: "encode-move-equations", skillEvidence: [evidence("representation-switching", "primary")], contentConcepts: ["parity"] },
        { milestoneId: "analyze-zero-effect-moves", skillEvidence: [evidence("proof-construction", "primary")], contentConcepts: ["modular-reasoning"] },
        { milestoneId: "classify-reachability", skillEvidence: [evidence("invariants", "primary"), evidence("proof-construction", "supporting")], contentConcepts: ["parity"] }
      ], extensionIds: [], difficulty: "strong" },
      { id: "triple-flip-transfer", role: "transfer", prerequisiteStageIds: ["triple-flip-core"], domains: ["combinatorics", "number-theory"], contentConcepts: ["parity", "modular-reasoning", "counting-structure"], skillEvidence: [evidence("precision-checking", "primary"), evidence("generalization", "supporting")], milestones: [{ milestoneId: "prove-sufficiency-by-counting", skillEvidence: [evidence("precision-checking", "primary")], contentConcepts: ["counting-structure", "parity"] }], extensionIds: ["two-lamp-transfer", "move-multiplicity"], difficulty: "strong"
      }
    ]
  })
};
export const oxfordDTripleFlipCircleEntry = authorCuratedProblem(oxfordDTripleFlipCircleSpec);

export const dirichletBatchDEntries = Object.freeze([
  oxfordDThreeReversalPermutationsEntry,
  oxfordDDivisorStepGeometryEntry,
  oxfordDTripleFlipCircleEntry
] as const);
